### ISSUE TITLE
Improve contributor list display on small screens

### ISSUE THREAD

**Issue by tcosmo** [cosearch-lab/cosearch#1]
The list should wrap and become multi-line

<img width="462" alt="Capture d’écran 2024-08-17 à 12 24 44" src="https://github.com/user-attachments/assets/c337eecc-1c5a-4963-9a58-8606c4eb995b">

**Comment by Nil2000** [comment]
Hi @tcosmo , I would like to work on this. But after setting up locally got this in the `localhost:5173`.
![image](https://github.com/user-attachments/assets/db550d4b-1bc9-4fc5-8317-935f563414df)

Got some terminal errors as well.
![image](https://github.com/user-attachments/assets/b77d15e8-8b95-4652-9676-66fd5afc5bc1)

Ok probably I also require the `Api` repo as well right? [this repo](https://github.com/cosearch-lab/cosearch-api)

**Comment by tcosmo** [comment]
Hello @Nil2000, thank you very much for contributing on cosearch!

Yeah, you need to connect to the API, the easiest way to get going is to use bbchallenge's staging cosearch api:

- Create `.env` at the root
- Add `PUBLIC_API_URL=https://api-staging-cosearch.bbchallenge.org/`

Alternatively you can also run [cosearch-api](https://github.com/cosearch-lab/cosearch-api) locally, but the staging API has real-world data in it.

I have improved [README.md](https://github.com/cosearch-lab/cosearch/blob/main/README.md), let me know if it is still unclear!

Also, feel free to join us on [cosearch Discord's server](https://discord.gg/ZuuRy8FE3R) :)
